on:
  push:
    branches:
      - main

jobs:
  deploy_satisfactory_planner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Prepare files for deployment
        run: |
          mkdir -p deploy_directory/public_html
          mkdir -p deploy_directory/private
          mkdir -p deploy_directory/static

          # Prepare public files
          rsync -av --progress ./public/ deploy_directory/public_html/ \
            --exclude '.htaccess' \
            --exclude 'image' \
            --exclude 'index.php'

          # Prepare private files
          rsync -av --progress ./private/ deploy_directory/private/ \
            --exclude 'autoload.php' \
            --exclude 'config/settings.php'

          # Prepare static files
          rsync -av --progress ./static/ deploy_directory/static/

      - name: Deploy public files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_SERVER }}
          port: 22
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: deploy_directory/public_html/
          remote_path: /home/timmy/domains/satisfactoryplanner.timmygamer.nl
          delete_remote_files: false
          sftp_only: true

      - name: Deploy private files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_SERVER }}
          port: 22
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: deploy_directory/private/
          remote_path: /home/timmy/domains/satisfactoryplanner.timmygamer.nl
          delete_remote_files: false
          sftp_only: true

      - name: Deploy static files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_SERVER }}
          port: 22
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: deploy_directory/static/
          remote_path: /home/timmy/domains/satisfactoryplanner.timmygamer.nl
          delete_remote_files: false
          sftp_only: true
