on:
  push:
    branches:
      - main
    paths:
      - public/**
      - static/**
      - private/**
  workflow_dispatch:
    inputs:
      disable_email:
        description: "Skip sending the update email?"
        required: false
        default: "false"
        type: boolean

jobs:
  deploy_satisfactory_planner:
    runs-on: ubuntu-latest
    steps:
      - name: Enable Maintenance Mode
        run: |
          curl -X POST https://satisfactoryplanner.timmygamer.nl/api/maintenance \
            -H "Authorization: Bearer ${{ secrets.MAINTENANCE_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"enabled": true}' 

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Prepare files for deployment
        run: |
          mkdir -p deploy_directory/public_html
          mkdir -p deploy_directory/private
          mkdir -p deploy_directory/static

          # Prepare public files
          rsync -av --progress ./public/ deploy_directory/public_html/ \
            --exclude '.htaccess' \
            --exclude 'image' \
            --exclude 'TypeScript' \
            --exclude 'index.php'

          # Prepare private files
          rsync -av --progress ./private/ deploy_directory/private/ \
            --exclude 'autoload.php' \
            --exclude 'config/settings.php'

          # Prepare static files
          rsync -av --progress ./static/ deploy_directory/static/

      - name: Deploy public files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_SERVER }}
          port: 22
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: deploy_directory/public_html/
          remote_path: /home/timmy/domains/satisfactoryplanner.timmygamer.nl
          delete_remote_files: false
          sftp_only: true

      - name: Deploy private files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_SERVER }}
          port: 22
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: deploy_directory/private/
          remote_path: /home/timmy/domains/satisfactoryplanner.timmygamer.nl
          delete_remote_files: false
          sftp_only: true

      - name: Deploy static files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_SERVER }}
          port: 22
          password: ${{ secrets.SFTP_PASSWORD }}
          local_path: deploy_directory/static/
          remote_path: /home/timmy/domains/satisfactoryplanner.timmygamer.nl
          delete_remote_files: false
          sftp_only: true

      - name: Disable Maintenance Mode
        run: |
          curl -X POST https://satisfactoryplanner.timmygamer.nl/api/maintenance \
            -H "Authorization: Bearer ${{ secrets.MAINTENANCE_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"enabled": false}'  

      - name: Get Version
        id: version
        run: |
          version=$(jq -r '.[0].version' public/changelog.json)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Check if Round Version
        id: round
        run: |
          if [[ "${{ steps.version.outputs.version }}" =~ ^[0-9]+\.[0-9]+\.0$ ]]; then
            echo "is_round=true" >> $GITHUB_OUTPUT
          else
            echo "is_round=false" >> $GITHUB_OUTPUT
          fi

      - name: Send Update Email
        if: >
          (
            (github.event_name == 'workflow_dispatch' && inputs.disable_email != 'true') ||
            (github.event_name == 'push' && !contains(github.event.head_commit.message, '[no email]'))
          )
          && steps.round.outputs.is_round == 'true'
        run: |
          curl -X POST https://satisfactoryplanner.timmygamer.nl/api/send-update-email \
            -H "Authorization: Bearer ${{ secrets.MAINTENANCE_TOKEN }}" \
            -H "Content-Type: application/json"
